# Generated by Django 4.2.27 on 2026-01-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='AssetPolicy',
            fields=[
                ('policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('useful_life', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('method', models.CharField(choices=[('Straight Line', 'Straight Line'), ('Reducing Balance', 'Reducing Balance')], max_length=20)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'asset_policy',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('depreciation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depreciation_date', models.DateField()),
                ('method', models.CharField(max_length=100)),
                ('computation', models.CharField(max_length=100)),
                ('book_value', models.FloatField()),
                ('depreciation_rate', models.FloatField()),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.account')),
            ],
            options={
                'db_table': 'depreciation',
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('gl_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('gl_code', models.IntegerField()),
                ('source_type', models.CharField(choices=[('WIP', 'WIP'), ('FA', 'Fixed Asset'), ('EXPENSE', 'Expense')], max_length=20)),
                ('ref_type', models.CharField(choices=[('Expense', 'Expense'), ('Depreciation', 'Depreciation')], max_length=20)),
                ('account_code', models.CharField(max_length=255)),
                ('gl_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('debit_amount', models.FloatField(default=0)),
                ('credit_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.account')),
            ],
            options={
                'db_table': 'general_ledger',
            },
        ),
        migrations.CreateModel(
            name='GLAllocation',
            fields=[
                ('gl_allocation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('allocation_type', models.CharField(choices=[('WIP', 'WIP'), ('FA', 'Fixed Asset'), ('EXPENSE', 'Expense')], max_length=20)),
                ('allocation_amount', models.FloatField()),
                ('account_code', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.generalledger')),
            ],
            options={
                'db_table': 'gl_allocation',
            },
        ),
        migrations.CreateModel(
            name='WorkInProgress',
            fields=[
                ('wip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wip_code', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('progress', 'Progress'), ('completed', 'Completed'), ('capitalized', 'Capitalized')], max_length=20)),
                ('total_amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('gl_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixed_asset.glallocation')),
            ],
            options={
                'db_table': 'work_in_progress',
            },
        ),
        migrations.CreateModel(
            name='WIPItem',
            fields=[
                ('wip_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('cost_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.workinprogress')),
            ],
            options={
                'db_table': 'wip_item',
            },
        ),
        migrations.CreateModel(
            name='FixedAssetRegister',
            fields=[
                ('register_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fixed_asset_code', models.CharField(max_length=255)),
                ('acquisition_date', models.DateField()),
                ('auto_increment', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('WIP', 'WIP'), ('DIRECT', 'Direct')], max_length=20)),
                ('asset_status', models.CharField(choices=[('Finished', 'Finished'), ('Ready to Use', 'Ready to Use'), ('No Depreciation', 'No Depreciation')], max_length=30)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_model', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_group', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_type', models.CharField(choices=[('MAIN', 'MAIN'), ('COMPONENT', 'COMPONENT')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('useful_life', models.IntegerField()),
                ('period', models.CharField(choices=[('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], max_length=30)),
                ('capitalization_date', models.DateTimeField()),
                ('home_currency', models.CharField(max_length=3)),
                ('transaction_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.FloatField()),
                ('acquisition_cost', models.FloatField()),
                ('home_acquisition_cost', models.FloatField()),
                ('residual_value', models.FloatField()),
                ('transportation_fee', models.FloatField()),
                ('tax', models.FloatField()),
                ('other_fee', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('computation', models.CharField(choices=[('DAY', 'DAY'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR')], max_length=30)),
                ('addition_amount', models.FloatField()),
                ('depreciation_method', models.CharField(choices=[('Straight Line', 'Straight Line'), ('Reducing Balance', 'Reducing Balance')], max_length=30)),
                ('current_nbv', models.FloatField()),
                ('depreciation_account', models.CharField(max_length=255)),
                ('expense_account', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.account')),
                ('gl_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixed_asset.glallocation')),
                ('wip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixed_asset.workinprogress')),
            ],
            options={
                'db_table': 'fixed_asset_register',
            },
        ),
        migrations.CreateModel(
            name='DepreciationEvent',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depreciation_date', models.DateField()),
                ('depreciation_amount', models.FloatField()),
                ('accumulated_depreciation', models.FloatField()),
                ('nbv_depreciation', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depreciation', models.ForeignKey(db_column='depreciation_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.depreciation')),
                ('policy', models.ForeignKey(db_column='policy_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.assetpolicy')),
                ('register', models.ForeignKey(db_column='register_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.fixedassetregister')),
            ],
            options={
                'db_table': 'depreciation_event',
            },
        ),
        migrations.AddField(
            model_name='depreciation',
            name='register',
            field=models.ForeignKey(db_column='register_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.fixedassetregister'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_code', models.CharField(max_length=255)),
                ('dept_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.company')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.AddField(
            model_name='assetpolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.company'),
        ),
        migrations.AddField(
            model_name='assetpolicy',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.department'),
        ),
        migrations.AddField(
            model_name='assetpolicy',
            name='depreciation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.depreciation'),
        ),
        migrations.AddField(
            model_name='assetpolicy',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.fixedassetregister'),
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('asset_disposal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disposal_date', models.DateField()),
                ('disposal_type', models.CharField(choices=[('Sale', 'Sale'), ('Scrap', 'Scrap'), ('WriteOff', 'Write Off')], max_length=20)),
                ('computation', models.CharField(choices=[('Gain', 'Gain'), ('Loss', 'Loss')], max_length=10)),
                ('proceeds_amount', models.FloatField()),
                ('book_value', models.FloatField()),
                ('gain_loss', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('policy', models.ForeignKey(db_column='policy_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.assetpolicy')),
                ('register', models.ForeignKey(db_column='register_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.fixedassetregister')),
            ],
            options={
                'db_table': 'asset_disposal',
            },
        ),
        migrations.CreateModel(
            name='AssetDepartmentHistory',
            fields=[
                ('dept_history_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.department')),
                ('register', models.ForeignKey(db_column='register_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.fixedassetregister')),
            ],
            options={
                'db_table': 'asset_dept_history',
            },
        ),
        migrations.CreateModel(
            name='AssetAdjustment',
            fields=[
                ('asset_adjustment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('adjustment_date', models.DateTimeField()),
                ('adjustment_type', models.CharField(choices=[('Additional Cost', 'Additional Cost'), ('Changing Useful life', 'Changing Useful Life'), ('Changing Depreciation Method', 'Changing Depreciation Method'), ('Disposal', 'Disposal'), ('Write Off', 'Write Off'), ('Impairment', 'Impairment'), ('Transfer Location', 'Transfer Location'), ('Partial Disposal', 'Partial Disposal'), ('Component Repalcement', 'Component Replacement'), ('Residual Value Change', 'Residual Value Change'), ('Revaluation', 'Revaluation'), ('Overhaul Cost', 'Overhaul Cost')], max_length=50)),
                ('old_value', models.FloatField()),
                ('new_value', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('register', models.ForeignKey(db_column='register_id', on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.fixedassetregister')),
            ],
            options={
                'db_table': 'asset_adjustment',
            },
        ),
    ]
